/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2b52bc90-5656-4d90-91da-135e26adabd6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_lR73LDozj",
    "aws_user_pools_web_client_id": "7q55tjmmatqhufvngq8u8cqjac",
    "oauth": {}
};


export default awsmobile;
